config/routes.rb
Rails.application.routes.draw do

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :historico_laborals
  resources :empregadors
  resources :documentos
  resources :pessoa_fisicas

  root 'homepage#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/index.html.erb
<% flash.each do |key, value| %>
  <div class="<% flash_class(key) %>">
    <% value %>
  </div>
<% end %>
<div class="container-fluid" style="background-image: linear-gradient(to bottom right, #0F1828 , #2A446F); width: 100%; height: calc(100vh - 56px); padding-left: 30px; padding-right: 30px">
  <h1 class="display-4" style="color: #eeeeee; padding-top: 150px">DESAFIO<span style="font-weight: bold"> WEBTECH</span></h1>
  <p class="lead" style="color:#eeeeee">Essa aplicação permite a criação de Históricos Laborais a Segurados da Previdencia Social.</p>
  <hr class="my-4" style="border-color: #BBBBBB">

  <p style="color: #DADADA"> Abaixo poderão ser registrados cada um dos elementos necessários para a criação do Histórico Laboral.</p>
  <br><br><br>

        <%= link_to 'Segurados', pessoa_fisicas_path, class: "btn btn-outline-light btn-lg"%>

        <%=link_to 'Empregadores', empregadors_path , class: "btn btn-outline-light btn-lg"%>

        <%=link_to 'Documentos', documentos_path, class: "btn btn-outline-light btn-lg"%>

        <%=link_to 'Cadastro de Históricos Laborais', historico_laborals_path, class: "btn btn-outline-light btn-lg"%>
 </div>