config/routes.rb
Rails.application.routes.draw do

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :historico_laborals
  resources :empregadors
  resources :documentos
  resources :pessoa_fisicas

  root 'homepage#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/historico_laboral.rb
class HistoricoLaboral < ApplicationRecord
  belongs_to :empregador
  belongs_to :pessoa_fisica
  belongs_to :documento
end

app/controllers/historico_laborals_controller.rb
class HistoricoLaboralsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_historico_laboral, only: [:show, :edit, :update, :destroy]
  before_action :set_pessoa_fisica_options, only:[:new, :edit, :update, :create]
  before_action :set_empregador_options, only:[:new, :edit, :update, :create]
  before_action :documento_pessoa, only:[:new, :edit, :update, :create]


  # GET /historico_laborals
  # GET /historico_laborals.json
  def index
    @historico_laborals = HistoricoLaboral.all
  end

  # GET /historico_laborals/1
  # GET /historico_laborals/1.json
  def show
  end

  # GET /historico_laborals/new
  def new
    @historico_laboral = HistoricoLaboral.new
  end

  # GET /historico_laborals/1/edit
  def edit
  end

  # POST /historico_laborals
  # POST /historico_laborals.json
  def create
    @historico_laboral = HistoricoLaboral.new(historico_laboral_params)

    respond_to do |format|
      if @historico_laboral.save
        format.html { redirect_to historico_laborals_url, notice: 'Histórico laboral foi criado com sucesso!' }
        format.json { render :show, status: :created, location: @historico_laboral }
      else
        format.html { render :new }
        format.json { render json: @historico_laboral.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /historico_laborals/1
  # PATCH/PUT /historico_laborals/1.json
  def update
    respond_to do |format|
      if @historico_laboral.update(historico_laboral_params)
        format.html { redirect_to historico_laborals_url, notice: 'Histórico laboral foi atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @historico_laboral }
      else
        format.html { render :edit }
        format.json { render json: @historico_laboral.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /historico_laborals/1
  # DELETE /historico_laborals/1.json
  def destroy
    @historico_laboral.destroy
    respond_to do |format|
      format.html { redirect_to historico_laborals_url, notice: 'Historico laboral was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def documento_pessoa
    @documento_pessoa = Documento.all.pluck(:nome, :id)
  end
  def set_empregador_options
    @empregador_options = Empregador.all.pluck(:nome, :id)
  end
  def set_pessoa_fisica_options
    @pessoa_fisica_options =  PessoaFisica.all.pluck(:nome, :id)
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_historico_laboral
      @historico_laboral = HistoricoLaboral.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def historico_laboral_params
      params.require(:historico_laboral).permit(:nome_identificador, :empregador_id, :pessoa_fisica_id, :documento_id, :anos, :meses, :dias)
    end
end

app/helpers/historico_laborals_helper.rb
module HistoricoLaboralsHelper
end

app/views/historico_laborals/_form.html.erb
<%= form_with(model: historico_laboral, local: true) do |form| %>
  <% if historico_laboral.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(historico_laboral.errors.count, "error") %> prohibited this historico_laboral from being saved:</h2>

      <ul>
      <% historico_laboral.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="col-6">

      <%if params[:acao] == 'docs' %>

      <div class="form-group" id="documento-field">
        <%= form.label :documento_id %>
        <%= form.select("documento_id",@documento_pessoa, {selected: params[:documento_id]}, class:'custom-select')%>
      </div>
      <%else  %>
        <div class="form-group" id="documento-field">
          <%= form.label :documento_id %>
          <%= form.select("documento_id",@documento_pessoa, {include_blank: "Selecione"} , class:'custom-select', onchange: 'carregarDoc()', required: true )  %>
        </div>
      <%end %>
      <div class="form-group">
        <%= form.label :nome_identificador, 'Nome Identificador do Histórico' %>
        <%= form.text_field :nome_identificador, class: "form-control", required: true  %>
      </div>

      <div class="form-group">
        <%= form.label :pessoa_fisica_id %>
        <%= form.select("pessoa_fisica_id",@pessoa_fisica_options, {include_blank: "Selecione"} , class:'custom-select', required: true)  %>
      </div>
      <div class="form-group">
        <%= form.label :empregador_id %>
        <%= form.select("empregador_id",@empregador_options, {include_blank: "Selecione"}, class:'custom-select', required: true ) %>
      </div>


    <div class="row">
      <div class="form-group col-4">
        <%= form.label :anos %>
        <%= form.number_field :anos, class: "form-control", required: true  %>
      </div>

      <div class="form-group col-4">
        <%= form.label :meses %>
        <%= form.number_field :meses, class: "form-control", required: true  %>
      </div>

      <div class="form-group col-4">
        <%= form.label :dias %>
        <%= form.number_field :dias, class: "form-control", required: true  %>
      </div>
    </div>
    <%if params[:action] == 'edit' %>
      <div class="actions" id="btn-salvar" hidden>
        <%= form.submit "Salvar", class:"btn btn-success", id: 'botao-salvar'%>
      </div>
    <%else %>
      <div class="actions" id="btn-salvar">
        <%= link_to 'Voltar', historico_laborals_path, class:"btn btn-light"%>

        <%= form.submit "Salvar", class:"btn btn-success", style: 'float:right'%>
      </div>
    <%end %>
<!--    <div class="actions">-->
      <%#= link_to 'Voltar', historico_laborals_path, class:"btn btn-light" %>
      <%#= form.submit "Salvar", class:"btn btn-success", style: 'float:right', onclick: 'salvarDoc()' %>
<!--    </div>-->
<% end %>

  </div>
  <div class="col-6">
    <%if params[:acao] == 'docs' %>
      <iframe src=<%= url_for(Documento.find(params[:documento_id]).doc)%> width="700" height="600" style="border: none;"> </iframe>
    <%elsif params[:action]=='edit' %>
      <iframe src=<%= url_for(HistoricoLaboral.find(params[:id]).documento.doc)%> width="700" height="600" style="border: none;"> </iframe>
    <%end %>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
  function carregarDoc(){
     return $('#historico_laboral_documento_id').val()
  }
</script>
<!--<script type="text/javascript" charset="utf-8">-->
<!--  function mostraDocs(teste){-->
<!--      $('#documento-field').attr("hidden", false)-->
<!--      console.log(teste[1])-->
<!--  }-->
<!--</script>-->
<!--<script type="text/javascript" charset="utf-8">-->
<!--  var docs = new Array();-->
  <%# for doc in @documento_pessoa %>
<!--  docs.push(new Array(<%#=doc[1] %>,'<%#= doc[0] %>', <%#=doc[2] %>));-->
  <%#end %>

<!--  function pessoaSelected() {-->
<!--      pessoa_id = $('#historico_laboral_pessoa_fisica_id').val();-->
<!--      options = $('historico_laboral_documento_id').options;-->
<!--      docs.forEach(function(doc) {-->
<!--          if (doc[0] == pessoa_id) {-->
<!--              options[options.length] = new Option(doc[1], doc[2]);-->
<!--          }-->
<!--      });-->
<!--      if (options.length == 1) {-->
<!--          $('#documento-field').hide();-->
<!--      } else {-->
<!--          $('#documento-field').show();-->
<!--      }-->
<!--  }-->

<!--  $( document ).ready(function() {-->
<!--      pessoaSelected();-->
<!--      $('#documento-field').hide();-->
<!--      $('#historico_laboral_pessoa_fisica_id').observe('change', pessoaSelected);-->
<!--  });-->
<!--</script>-->

app/views/historico_laborals/edit.html.erb
<h1>Histórico Laboral</h1>
<fieldset id='formulario' disabled>
  <%= render 'form', historico_laboral: @historico_laboral %>
</fieldset>

<div style="margin-top: -10px">
    <div class="row">
      <div class="col-3">
        <%= link_to 'Voltar', historico_laborals_path, class:"btn btn-light"%>
      </div>
      <div class="col-3" style="float: right">
        <button class="btn btn-success" hidden id='btn-salvar2' onclick="salvar()" style="float: right; margin-left: 4px">
        Salvar
      </button>
        <button id='btn-cancelar' onclick="cancelar()" class="btn btn-danger" hidden style="float: right">
          Cancelar
        </button>
        <button class="btn btn-info" id='btn-editar' onclick="editar()" style="float: right">
          Editar
        </button>
      </div>
      <div class="col-6">

      </div>
    </div>
  </div>
<% javascript_include_tag 'formulario.js'%>

app/views/historico_laborals/index.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <%= value %>
  </div>
<% end %>
<div class="row">
  <div class="col-10">
    <h1>Históricos Laborais</h1>
  </div>
  <div class="col-2">
    <%= link_to 'Novo Histórico Laboral', new_historico_laboral_path, class:"btn btn-desafio"  %>
  </div>
</div>


<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Nome identificador</th>
      <th>Empregador</th>
      <th>Segurado</th>
      <th>Documento</th>
      <th>Dias</th>
      <th colspan="3"> Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @historico_laborals.each do |historico_laboral| %>
      <tr>
        <td><%= historico_laboral.nome_identificador %></td>
        <td><%= historico_laboral.empregador.nome %></td>
        <td><%= historico_laboral.pessoa_fisica.nome %></td>
        <td><%= historico_laboral.documento.nome %></td>
        <td><%= (historico_laboral.anos)*365 + (historico_laboral.meses)*30 + (historico_laboral.dias)  %></td>
<!--        <td><%#= link_to 'Visualizar', historico_laboral %></td>-->
        <td><%= link_to 'Visualizar', edit_historico_laboral_path(historico_laboral) %></td>
        <td><%= link_to 'Excluir', historico_laboral, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Voltar',root_path, class:"btn btn-light" %>

app/views/historico_laborals/new.html.erb
<h1>Novo Histórico Laboral</h1>

<%= render 'form', historico_laboral: @historico_laboral %>

app/views/historico_laborals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome identificador:</strong>
  <%= @historico_laboral.nome_identificador %>
</p>

<p>
  <strong>Empregador:</strong>
  <%= @historico_laboral.empregador.nome %>
</p>

<p>
  <strong>Pessoa fisica:</strong>
  <%= @historico_laboral.pessoa_fisica.nome %>
</p>

<p>
  <strong>Documento:</strong>
  <%= @historico_laboral.documento.nome %>
</p>

<p>
  <strong>Anos:</strong>
  <%= @historico_laboral.anos %>
</p>

<p>
  <strong>Meses:</strong>
  <%= @historico_laboral.meses %>
</p>

<p>
  <strong>Dias:</strong>
  <%= @historico_laboral.dias %>
</p>


<%= link_to 'Edit', edit_historico_laboral_path(@historico_laboral) %> |
<%= link_to 'Back', historico_laborals_path %>