config/routes.rb
Rails.application.routes.draw do

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :historico_laborals
  resources :empregadors
  resources :documentos
  resources :pessoa_fisicas

  root 'homepage#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/documento.rb
class Documento < ApplicationRecord
  has_one_attached :doc, :dependent => :destroy
  belongs_to :pessoa_fisica , :optional => true
  has_one :historico_laboral , :dependent => :destroy
end

app/controllers/documentos_controller.rb
class DocumentosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_documento, only: [:show, :edit, :update, :destroy]
  before_action :set_pessoa_fisica_options, only:[:new, :edit, :update, :create]

  # GET /documentos
  # GET /documentos.json
  def index
    @documentos = Documento.all
  end

  # GET /documentos/1
  # GET /documentos/1.json
  def show
  end

  # GET /documentos/new
  def new
    @documento = Documento.new
  end

  # GET /documentos/1/edit
  def edit
  end

  # POST /documentos
  # POST /documentos.json
  def create
    @documento = Documento.new(documento_params)

    respond_to do |format|
      if @documento.save
        format.html { redirect_to new_historico_laboral_path(documento_id: @documento.id, acao: 'docs')}
        format.json { render :show, status: :created, location: @documento }
      else
        format.html { render :new }
        format.json { render json: @documento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documentos/1
  # PATCH/PUT /documentos/1.json
  def update
    respond_to do |format|
      if @documento.update(documento_params)
        format.html { redirect_to documentos_url, notice: 'Documento foi atualizado com sucesso!' }
        format.json { render :show, status: :ok, location: @documento }
      else
        format.html { render :edit }
        format.json { render json: @documento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documentos/1
  # DELETE /documentos/1.json
  def destroy
    @documento.destroy
    respond_to do |format|
      format.html { redirect_to documentos_url, notice: 'Documento excluído com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
  def set_pessoa_fisica_options
    @pessoa_fisica_options =  PessoaFisica.all.pluck(:nome, :id)
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_documento
      @documento = Documento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def documento_params
      params.require(:documento).permit(:nome, :doc, :pessoa_fisica_id, :id)
    end
end

app/helpers/documentos_helper.rb
module DocumentosHelper
end

app/views/documentos/_form.html.erb
<%= form_with(model: documento, local: true) do |form| %>
  <% if documento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(documento.errors.count, "error") %> prohibited this documento from being saved:</h2>

      <ul>
      <% documento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nome %>
    <%= form.text_field :nome, class: "form-control", required: true %>
  </div>
  <small>Selecione um arquivo no formato PDF</small>

  <div class="custom-file">
    <%=form.label :doc, class: "custom-file-input" %>
    <%=form.file_field :doc , class:"custom-file-label", style: 'width:100%' %>

  </div>
<!--  <div class="field">-->
    <%#=form.label :pessoa_fisica_id %>
    <%#= form.select("pessoa_fisica_id",@pessoa_fisica_options, {include_blank: "Selecione"}) %>
<!--  </div>-->
  <div class="actions" style="padding-top: 15px">
    <%= link_to 'Voltar', documentos_path , class:"btn btn-light"%>
<!--      <i class="fa fa-arrow-left">Voltar</i>-->
      <%#end %>
    <%= form.submit "Salvar", class:"btn btn-success", style: 'float:right' %>
  </div>
<% end %>

app/views/documentos/edit.html.erb
<h1>Documento</h1>

<%= render 'form', documento: @documento %>

app/views/documentos/index.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
    <%= value %>
  </div>
<% end %>
<div class="row">
  <div class="col-10">
    <h1>Documentos</h1>
  </div>
  <div class="col-2">
    <%= link_to 'Novo Documento', new_documento_path, class:"btn btn-desafio", style:'float:right'  %>
  </div>
</div>


<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"> Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @documentos.each do |documento| %>
      <tr>
        <td><%= documento.nome %></td>
        <td><%= link_to 'Visualizar', documento %></td>
<!--        <td><%#= link_to 'Editar', edit_documento_path(documento) %></td>-->
        <td><%= link_to 'Excluir', documento, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Voltar',root_path, class:"btn btn-light" %>

app/views/documentos/new.html.erb
<h1>Novo Documento</h1>

<%= render 'form', documento: @documento %>
<div style="float:right;">
  <small>Você será direcionado ao cadastro de Históricos Laborais.</small>
</div>

app/views/documentos/show.html.erb
<h1>Documento</h1>

<div class="row">
  <div class="col-6">
    <strong>Nome:</strong>
    <%= @documento.nome %>
  </div>
  <div class="col-6">
    <%= link_to 'Abrir em nova aba', @documento.doc, target: :_blank , class: 'btn btn-info', style:'float:right'%>


  </div>
</div>

<div align="center">
  <iframe src=<%= url_for(@documento.doc)%> width="900" height="600" style="border: none;"> </iframe>
</div>
<%= link_to 'Alterar Documento', edit_documento_path(@documento), class: 'btn btn-primary', style:'float:right' %>
<%= link_to 'Voltar', documentos_path, class: 'btn btn-light', style:'float:left' %>